### PR TITLE
adds error message to frontend if try to upload anything other than x…

### PR DESCRIPTION
**Pull request by benptc**
…ml, dat, jpg, or zip to the dropzone. also allows xml upload via dropzone independently from dat, previously you had to upload together or it would be generated automatically

Fixes issue #123 (along with previous PR)

### CODE REVIEW

**Comment by benptc** [comment]
Message looks like:

Screen Shot 2020-04-14 at 2 04 28 PM

**Comment by benptc** [comment]
> Nice! It would also be good to reject model targets

Do you know which file format model targets are? They would be rejected by this unless they are also packaged as a dat or a zip, in which case I'll need to look into some other distinguishing factor

**Comment by hobinjk-ptc** [comment]
They're also a zip but they contain XML with QCARConfig > Tracking > ModelTarget

**Comment by benptc** [comment]
Created issue #135 to follow up about the model targets

**Pull request merged**
