### PR TITLE
adding gl-worker.js, envelope.js and envelopeContents.js path for custom tools

### PR DESCRIPTION
**Pull request by afustePTC**

### CODE REVIEW

**Review by hobinjk-ptc — APPROVED** [review]
Good fix for now! Would be nice to make this a bit less repetitive in the future

**Review by benptc — APPROVED** [review]
Yep, this looks good!

**Comment by benptc** [comment]
> Good fix for now! Would be nice to make this a bit less repetitive in the future

@hobinjk-ptc Agreed. One way would just be to iterate through the *.js filenames in the objectDefaultFiles directory on the server, and perform this replacement for each match. Do you know of a better way?

**Comment by hobinjk-ptc** [comment]
Oh that would be reasonable. I was thinking more on how this duplicates code from /frames/:frameName

**Comment by benptc** [comment]
Oh right, that too! Seems like there would be an easy enough way to refactor them 👍

**Pull request merged**
